name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t your-image-name -f lib/Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 your-image-name

    - name: Wait for container to start
      run: sleep 10 # Adjust as necessary if your application takes longer to start

    - name: Execute npm start inside Docker container
      run: docker exec $(docker ps -qf "ancestor=your-image-name") npm start
